### ISSUE TITLE
com.tuya.connector.api.exceptions.ConnectorDelegateException: Error create retrofit delegate for connector : 

### ISSUE THREAD

**Issue by rayxie2046** [tuya/tuya-connector#29]
我遇到这个问题，不知如何处理，可能是与项目框架包冲突？
com.tuya.connector.api.exceptions.ConnectorDelegateException: Error create retrofit delegate for connector : cn.ac.xxx.admin.connector.HomeConnector.
 Cause: javassist.bytecode.DuplicateMemberException: duplicate method: queryGroup in cn.ac.xxx.admin.connector.$HomeConnector

**Comment by Edisonboy** [comment]
请问您项目中有引用 retrofit 的依赖吗，依赖的版本是多少。

**Comment by rayxie2046** [comment]
项目中没有用到 retrofit2， 我看了 retrofit2 在 tuya connector 依赖里面
[INFO] +- com.tuya:tuya-spring-boot-starter:jar:1.1.0:compile
[INFO] |  +- com.tuya:connector-spring-boot-starter:jar:1.1.0:compile
[INFO] |  |  +- com.tuya:connector-spring-boot-autoconfigure:jar:1.1.0:compile
[INFO] |  |  +- com.tuya:connector-spring:jar:1.1.0:compile
[INFO] |  |  \- com.tuya:connector-api:jar:1.1.0:compile
[INFO] |  |     +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.14.9:compile
[INFO] |  |     \- com.squareup.retrofit2:converter-gson:jar:2.9.0:compile
[INFO] |  +- com.tuya:tuya-api:jar:1.1.0:compile
[INFO] |  |  +- com.tuya:tuya-common:jar:1.1.0:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  \- com.tuya:tuya-messaging:jar:1.1.0:compile
[INFO] |     +- com.tuya:connector-messaging:jar:1.1.0:compile
[INFO] |     +- org.apache.pulsar:pulsar-client:jar:2.5.0:compile
[INFO] |     |  +- org.apache.pulsar:pulsar-client-api:jar:2.5.0:compile
[INFO] |     |  +- org.apache.pulsar:pulsar-transaction-common:jar:2.5.0:compile
[INFO] |     |  +- com.google.protobuf:protobuf-java-util:jar:3.11.4:compile
[INFO] |     |  +- org.apache.pulsar:protobuf-shaded:jar:2.1.0-incubating:compile
[INFO] |     |  +- org.checkerframework:checker-qual:jar:2.0.0:compile
[INFO] |     |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |     |  +- org.lz4:lz4-java:jar:1.5.0:compile
[INFO] |     |  +- com.github.luben:zstd-jni:jar:1.3.7-3:compile
[INFO] |     |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.60:compile
[INFO] |     |  +- org.bouncycastle:bcprov-jdk15on:jar:1.60:compile
[INFO] |     |  +- com.sun.activation:javax.activation:jar:1.2.0:compile
[INFO] |     |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |     +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |     \- org.reflections:reflections:jar:0.9.10:compile

**Comment by Edisonboy** [comment]
HomeConnector 是否定义了两个重复的方法：queryGroup() ?

**Comment by Edisonboy** [comment]
请问您使用的tuya-connector版本是多少

**Comment by rayxie2046** [comment]
com.tuya:tuya-spring-boot-starter:jar:1.1.0:

**Comment by Edisonboy** [comment]
试一下使用1.1.3版本呢

**Comment by rayxie2046** [comment]
我试试

**Comment by rayxie2046** [comment]
com.tuya.connector.api.exceptions.ConnectorDelegateException: Error create retrofit delegate for connector : cn.ac.xxx.admin.connector.HomeExtConnector.
 Cause: java.lang.NullPointerException

	at com.tuya.connector.api.core.delegate.DelegateFactory.forRetrofit(DelegateFactory.java:26)
	at com.tuya.connector.api.core.ConnectorProxy.invoke(ConnectorProxy.java:47)
	at com.sun.proxy.$Proxy11.addHome(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tuya.connector.api.plugin.Invocation.proceed(Invocation.java:29)
	at com.tuya.connector.api.error.ErrorProcessorInterceptor.intercept(ErrorProcessorInterceptor.java:29)
	at com.tuya.connector.api.plugin.Plugin.invoke(Plugin.java:26)
	at com.sun.proxy.$Proxy11.addHome(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tuya.connector.api.plugin.Invocation.proceed(Invocation.java:29)
	at com.tuya.connector.api.context.ContextInterceptor.intercept(ContextInterceptor.java:30)
	at com.tuya.connector.api.plugin.Plugin.invoke(Plugin.java:26)
	at com.sun.proxy.$Proxy11.addHome(Unknown Source) #

**Comment by Edisonboy** [comment]
可以贴一下NullPointerException具体的异常吗

**Comment by rayxie2046** [comment]
问题解决，少一个 注解 @Body
@PUT("/v1.0/homes/{home_id}")
TuyaResult update(@Path("home_id") Integer homeId, Map param);

**Comment by Edisonboy** [comment]
problem solved
